//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyCalendar.Models
{
    using System;
    
    public partial class events_get_events_by_loginID_prc_Result1
    {
        public int EventID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public Nullable<bool> IsFullDay { get; set; }
        public string ThemeColor { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
        public Nullable<int> Role { get; set; }
        public string EmpID { get; set; }
        public string Participant { get; set; }
        public string Title { get; set; }
        public string EventLocation { get; set; }
        public string LocCode { get; set; }
        public string EventType { get; set; }
    }
}
