//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyCalendar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CalendarDBEntities1 : DbContext
    {
        public CalendarDBEntities1()
            : base("name=CalendarDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<GetEventsTemp> GetEventsTemps { get; set; }
    
        public virtual ObjectResult<events_get_events_by_loginID_prc_Result1> GetEventsByID(Nullable<int> loginID, string eventType)
        {
            var loginIDParameter = loginID.HasValue ?
                new ObjectParameter("loginID", loginID) :
                new ObjectParameter("loginID", typeof(int));
    
            var eventTypeParameter = eventType != null ?
                new ObjectParameter("EventType", eventType) :
                new ObjectParameter("EventType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<events_get_events_by_loginID_prc_Result1>("GetEventsByID", loginIDParameter, eventTypeParameter);
        }
    }
}
